declare module 'lucide-react' {
  import { ComponentType, SVGProps } from 'react'
  
  export interface LucideProps extends SVGProps<SVGSVGElement> {
    size?: string | number
    color?: string
    strokeWidth?: string | number
  }
  
  export const FileText: ComponentType<LucideProps>
  export const DollarSign: ComponentType<LucideProps>
  export const CreditCard: ComponentType<LucideProps>
  export const Plus: ComponentType<LucideProps>
  export const Search: ComponentType<LucideProps>
  export const Filter: ComponentType<LucideProps>
  export const Eye: ComponentType<LucideProps>
  export const Edit: ComponentType<LucideProps>
  export const Trash2: ComponentType<LucideProps>
  export const Calendar: ComponentType<LucideProps>
  export const Clock: ComponentType<LucideProps>
  export const CheckCircle: ComponentType<LucideProps>
  export const XCircle: ComponentType<LucideProps>
  export const AlertCircle: ComponentType<LucideProps>
  export const User: ComponentType<LucideProps>
  export const Users: ComponentType<LucideProps>
  export const Shield: ComponentType<LucideProps>
  export const Zap: ComponentType<LucideProps>
  export const BarChart3: ComponentType<LucideProps>
  export const Mail: ComponentType<LucideProps>
  export const Phone: ComponentType<LucideProps>
  export const Building: ComponentType<LucideProps>
  export const MapPin: ComponentType<LucideProps>
  export const ExternalLink: ComponentType<LucideProps>
  export const Link: ComponentType<LucideProps>
  export const Copy: ComponentType<LucideProps>
  export const Check: ComponentType<LucideProps>
  export const X: ComponentType<LucideProps>
  export const ChevronDown: ComponentType<LucideProps>
  export const ChevronUp: ComponentType<LucideProps>
  export const ChevronLeft: ComponentType<LucideProps>
  export const ChevronRight: ComponentType<LucideProps>
  export const ArrowLeft: ComponentType<LucideProps>
  export const ArrowRight: ComponentType<LucideProps>
  export const Home: ComponentType<LucideProps>
  export const LogOut: ComponentType<LucideProps>
  export const Settings: ComponentType<LucideProps>
  export const Bell: ComponentType<LucideProps>
  export const Menu: ComponentType<LucideProps>
  export const Star: ComponentType<LucideProps>
  export const Heart: ComponentType<LucideProps>
  export const ThumbsUp: ComponentType<LucideProps>
  export const ThumbsDown: ComponentType<LucideProps>
  export const MessageCircle: ComponentType<LucideProps>
  export const MessageSquare: ComponentType<LucideProps>
  export const Send: ComponentType<LucideProps>
  export const Download: ComponentType<LucideProps>
  export const Upload: ComponentType<LucideProps>
  export const Save: ComponentType<LucideProps>
  export const RefreshCw: ComponentType<LucideProps>
  export const Loader2: ComponentType<LucideProps>
  export const RotateCcw: ComponentType<LucideProps>
  export const RotateCw: ComponentType<LucideProps>
  export const ZoomIn: ComponentType<LucideProps>
  export const ZoomOut: ComponentType<LucideProps>
  export const Maximize: ComponentType<LucideProps>
  export const Minimize: ComponentType<LucideProps>
  export const Move: ComponentType<LucideProps>
  export const Move3D: ComponentType<LucideProps>
  export const Rotate3D: ComponentType<LucideProps>
  export const Box: ComponentType<LucideProps>
  export const Package: ComponentType<LucideProps>
  export const Archive: ComponentType<LucideProps>
  export const Folder: ComponentType<LucideProps>
  export const FolderOpen: ComponentType<LucideProps>
  export const File: ComponentType<LucideProps>
  export const FileImage: ComponentType<LucideProps>
  export const FileVideo: ComponentType<LucideProps>
  export const FileAudio: ComponentType<LucideProps>
  export const FilePdf: ComponentType<LucideProps>
  export const FileSpreadsheet: ComponentType<LucideProps>
  export const FileCode: ComponentType<LucideProps>
  export const FileJson: ComponentType<LucideProps>
  export const FileXml: ComponentType<LucideProps>
  export const FileCsv: ComponentType<LucideProps>
  export const FileZip: ComponentType<LucideProps>
  export const FileArchive: ComponentType<LucideProps>
  export const FileBinary: ComponentType<LucideProps>
  export const FileDatabase: ComponentType<LucideProps>
  export const FileDocument: ComponentType<LucideProps>
  export const FileExcel: ComponentType<LucideProps>
  export const FilePowerpoint: ComponentType<LucideProps>
  export const FileWord: ComponentType<LucideProps>
  export const Files: ComponentType<LucideProps>
  export const FolderPlus: ComponentType<LucideProps>
  export const FolderMinus: ComponentType<LucideProps>
  export const FolderX: ComponentType<LucideProps>
  export const FolderCheck: ComponentType<LucideProps>
  export const FolderLock: ComponentType<LucideProps>
  export const FolderUnlock: ComponentType<LucideProps>
  export const FolderHeart: ComponentType<LucideProps>
  export const FolderStar: ComponentType<LucideProps>
  export const FolderUp: ComponentType<LucideProps>
  export const FolderDown: ComponentType<LucideProps>
  export const FolderLeft: ComponentType<LucideProps>
  export const FolderRight: ComponentType<LucideProps>
  export const FolderClosed: ComponentType<LucideProps>
  export const FolderOpen2: ComponentType<LucideProps>
  export const FolderClosed2: ComponentType<LucideProps>
  export const FolderOpen3: ComponentType<LucideProps>
  export const FolderClosed3: ComponentType<LucideProps>
  export const FolderOpen4: ComponentType<LucideProps>
  export const FolderClosed4: ComponentType<LucideProps>
  export const FolderOpen5: ComponentType<LucideProps>
  export const FolderClosed5: ComponentType<LucideProps>
  export const FolderOpen6: ComponentType<LucideProps>
  export const FolderClosed6: ComponentType<LucideProps>
  export const FolderOpen7: ComponentType<LucideProps>
  export const FolderClosed7: ComponentType<LucideProps>
  export const FolderOpen8: ComponentType<LucideProps>
  export const FolderClosed8: ComponentType<LucideProps>
  export const FolderOpen9: ComponentType<LucideProps>
  export const FolderClosed9: ComponentType<LucideProps>
  export const FolderOpen10: ComponentType<LucideProps>
  export const FolderClosed10: ComponentType<LucideProps>
  export const FolderOpen11: ComponentType<LucideProps>
  export const FolderClosed11: ComponentType<LucideProps>
  export const FolderOpen12: ComponentType<LucideProps>
  export const FolderClosed12: ComponentType<LucideProps>
  export const FolderOpen13: ComponentType<LucideProps>
  export const FolderClosed13: ComponentType<LucideProps>
  export const FolderOpen14: ComponentType<LucideProps>
  export const FolderClosed14: ComponentType<LucideProps>
  export const FolderOpen15: ComponentType<LucideProps>
  export const FolderClosed15: ComponentType<LucideProps>
  export const FolderOpen16: ComponentType<LucideProps>
  export const FolderClosed16: ComponentType<LucideProps>
  export const FolderOpen17: ComponentType<LucideProps>
  export const FolderClosed17: ComponentType<LucideProps>
  export const FolderOpen18: ComponentType<LucideProps>
  export const FolderClosed18: ComponentType<LucideProps>
  export const FolderOpen19: ComponentType<LucideProps>
  export const FolderClosed19: ComponentType<LucideProps>
  export const FolderOpen20: ComponentType<LucideProps>
  export const FolderClosed20: ComponentType<LucideProps>
  export const FolderOpen21: ComponentType<LucideProps>
  export const FolderClosed21: ComponentType<LucideProps>
  export const FolderOpen22: ComponentType<LucideProps>
  export const FolderClosed22: ComponentType<LucideProps>
  export const FolderOpen23: ComponentType<LucideProps>
  export const FolderClosed23: ComponentType<LucideProps>
  export const FolderOpen24: ComponentType<LucideProps>
  export const FolderClosed24: ComponentType<LucideProps>
  export const FolderOpen25: ComponentType<LucideProps>
  export const FolderClosed25: ComponentType<LucideProps>
  export const FolderOpen26: ComponentType<LucideProps>
  export const FolderClosed26: ComponentType<LucideProps>
  export const FolderOpen27: ComponentType<LucideProps>
  export const FolderClosed27: ComponentType<LucideProps>
  export const FolderOpen28: ComponentType<LucideProps>
  export const FolderClosed28: ComponentType<LucideProps>
  export const FolderOpen29: ComponentType<LucideProps>
  export const FolderClosed29: ComponentType<LucideProps>
  export const FolderOpen30: ComponentType<LucideProps>
  export const FolderClosed30: ComponentType<LucideProps>
  export const FolderOpen31: ComponentType<LucideProps>
  export const FolderClosed31: ComponentType<LucideProps>
  export const FolderOpen32: ComponentType<LucideProps>
  export const FolderClosed32: ComponentType<LucideProps>
  export const FolderOpen33: ComponentType<LucideProps>
  export const FolderClosed33: ComponentType<LucideProps>
  export const FolderClosed34: ComponentType<LucideProps>
  export const FolderOpen34: ComponentType<LucideProps>
  export const FolderClosed35: ComponentType<LucideProps>
  export const FolderOpen35: ComponentType<LucideProps>
  export const FolderClosed36: ComponentType<LucideProps>
  export const FolderOpen36: ComponentType<LucideProps>
  export const FolderClosed37: ComponentType<LucideProps>
  export const FolderOpen37: ComponentType<LucideProps>
  export const FolderClosed38: ComponentType<LucideProps>
  export const FolderOpen38: ComponentType<LucideProps>
  export const FolderClosed39: ComponentType<LucideProps>
  export const FolderOpen39: ComponentType<LucideProps>
  export const FolderClosed40: ComponentType<LucideProps>
  export const FolderOpen40: ComponentType<LucideProps>
  export const FolderClosed41: ComponentType<LucideProps>
  export const FolderOpen41: ComponentType<LucideProps>
  export const FolderClosed42: ComponentType<LucideProps>
  export const FolderOpen42: ComponentType<LucideProps>
  export const FolderClosed43: ComponentType<LucideProps>
  export const FolderOpen43: ComponentType<LucideProps>
  export const FolderClosed44: ComponentType<LucideProps>
  export const FolderOpen44: ComponentType<LucideProps>
  export const FolderClosed45: ComponentType<LucideProps>
  export const FolderOpen45: ComponentType<LucideProps>
  export const FolderClosed46: ComponentType<LucideProps>
  export const FolderOpen46: ComponentType<LucideProps>
  export const FolderClosed47: ComponentType<LucideProps>
  export const FolderOpen47: ComponentType<LucideProps>
  export const FolderClosed48: ComponentType<LucideProps>
  export const FolderOpen48: ComponentType<LucideProps>
  export const FolderClosed49: ComponentType<LucideProps>
  export const FolderOpen49: ComponentType<LucideProps>
  export const FolderClosed50: ComponentType<LucideProps>
  export const FolderOpen50: ComponentType<LucideProps>
  export const FolderClosed51: ComponentType<LucideProps>
  export const FolderOpen51: ComponentType<LucideProps>
  export const FolderClosed52: ComponentType<LucideProps>
  export const FolderOpen52: ComponentType<LucideProps>
  export const FolderClosed53: ComponentType<LucideProps>
  export const FolderOpen53: ComponentType<LucideProps>
  export const FolderClosed54: ComponentType<LucideProps>
  export const FolderOpen54: ComponentType<LucideProps>
  export const FolderClosed55: ComponentType<LucideProps>
  export const FolderOpen55: ComponentType<LucideProps>
  export const FolderClosed56: ComponentType<LucideProps>
  export const FolderOpen56: ComponentType<LucideProps>
  export const FolderClosed57: ComponentType<LucideProps>
  export const FolderOpen57: ComponentType<LucideProps>
  export const FolderClosed58: ComponentType<LucideProps>
  export const FolderOpen58: ComponentType<LucideProps>
  export const FolderClosed59: ComponentType<LucideProps>
  export const FolderOpen59: ComponentType<LucideProps>
  export const FolderClosed60: ComponentType<LucideProps>
  export const FolderOpen60: ComponentType<LucideProps>
  export const FolderClosed61: ComponentType<LucideProps>
  export const FolderOpen61: ComponentType<LucideProps>
  export const FolderClosed62: ComponentType<LucideProps>
  export const FolderOpen62: ComponentType<LucideProps>
  export const FolderClosed63: ComponentType<LucideProps>
  export const FolderOpen63: ComponentType<LucideProps>
  export const FolderClosed64: ComponentType<LucideProps>
  export const FolderOpen64: ComponentType<LucideProps>
  export const FolderClosed65: ComponentType<LucideProps>
  export const FolderOpen65: ComponentType<LucideProps>
  export const FolderClosed66: ComponentType<LucideProps>
  export const FolderOpen66: ComponentType<LucideProps>
  export const FolderClosed67: ComponentType<LucideProps>
  export const FolderOpen67: ComponentType<LucideProps>
  export const FolderClosed68: ComponentType<LucideProps>
  export const FolderOpen68: ComponentType<LucideProps>
  export const FolderClosed69: ComponentType<LucideProps>
  export const FolderOpen69: ComponentType<LucideProps>
  export const FolderClosed70: ComponentType<LucideProps>
  export const FolderOpen70: ComponentType<LucideProps>
  export const FolderClosed71: ComponentType<LucideProps>
  export const FolderOpen71: ComponentType<LucideProps>
  export const FolderClosed72: ComponentType<LucideProps>
  export const FolderOpen72: ComponentType<LucideProps>
  export const FolderClosed73: ComponentType<LucideProps>
  export const FolderOpen73: ComponentType<LucideProps>
  export const FolderClosed74: ComponentType<LucideProps>
  export const FolderOpen74: ComponentType<LucideProps>
  export const FolderClosed75: ComponentType<LucideProps>
  export const FolderOpen75: ComponentType<LucideProps>
  export const FolderClosed76: ComponentType<LucideProps>
  export const FolderOpen76: ComponentType<LucideProps>
  export const FolderClosed77: ComponentType<LucideProps>
  export const FolderOpen77: ComponentType<LucideProps>
  export const FolderClosed78: ComponentType<LucideProps>
  export const FolderOpen78: ComponentType<LucideProps>
  export const FolderClosed79: ComponentType<LucideProps>
  export const FolderOpen79: ComponentType<LucideProps>
  export const FolderClosed80: ComponentType<LucideProps>
  export const FolderOpen80: ComponentType<LucideProps>
  export const FolderClosed81: ComponentType<LucideProps>
  export const FolderOpen81: ComponentType<LucideProps>
  export const FolderClosed82: ComponentType<LucideProps>
  export const FolderOpen82: ComponentType<LucideProps>
  export const FolderClosed83: ComponentType<LucideProps>
  export const FolderOpen83: ComponentType<LucideProps>
  export const FolderClosed84: ComponentType<LucideProps>
  export const FolderOpen84: ComponentType<LucideProps>
  export const FolderClosed85: ComponentType<LucideProps>
  export const FolderOpen85: ComponentType<LucideProps>
  export const FolderClosed86: ComponentType<LucideProps>
  export const FolderOpen86: ComponentType<LucideProps>
  export const FolderClosed87: ComponentType<LucideProps>
  export const FolderOpen87: ComponentType<LucideProps>
  export const FolderClosed88: ComponentType<LucideProps>
  export const FolderOpen88: ComponentType<LucideProps>
  export const FolderClosed89: ComponentType<LucideProps>
  export const FolderOpen89: ComponentType<LucideProps>
  export const FolderClosed90: ComponentType<LucideProps>
  export const FolderOpen90: ComponentType<LucideProps>
  export const FolderClosed91: ComponentType<LucideProps>
  export const FolderOpen91: ComponentType<LucideProps>
  export const FolderClosed92: ComponentType<LucideProps>
  export const FolderOpen92: ComponentType<LucideProps>
  export const FolderClosed93: ComponentType<LucideProps>
  export const FolderOpen93: ComponentType<LucideProps>
  export const FolderClosed94: ComponentType<LucideProps>
  export const FolderOpen94: ComponentType<LucideProps>
  export const FolderClosed95: ComponentType<LucideProps>
  export const FolderOpen95: ComponentType<LucideProps>
  export const FolderClosed96: ComponentType<LucideProps>
  export const FolderOpen96: ComponentType<LucideProps>
  export const FolderClosed97: ComponentType<LucideProps>
  export const FolderOpen97: ComponentType<LucideProps>
  export const FolderClosed98: ComponentType<LucideProps>
  export const FolderOpen98: ComponentType<LucideProps>
  export const FolderClosed99: ComponentType<LucideProps>
  export const FolderOpen99: ComponentType<LucideProps>
  export const FolderClosed100: ComponentType<LucideProps>
  export const FolderOpen100: ComponentType<LucideProps>
}
